name: Set Up Maven
description: Set up Maven with github token.
inputs:
  token:
    description: "GitHub token"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up Apache Maven and JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: 21
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME # env variable for username
        server-password: MAVEN_TOKEN # env variable for token
    - name: Set Maven env
      env:
        MAVEN_USERNAME: github
        MAVEN_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        echo "MAVEN_USERNAME=${MAVEN_USERNAME}" >> $GITHUB_ENV
        echo "MAVEN_TOKEN=${MAVEN_TOKEN}" >> $GITHUB_ENV