# This file contains the parameters for the credentials used in the workflows.
- name: OTN_USERID
  value: ""
  description: Oracle single sign-on userid.
- name: OTN_PASSWORD
  value: ""
  description: Password for Oracle single sign-on userid.
- name: WLS_PSW
  value: ""
  description: Password for WebLogic Server.
# Git credentials
- name: USER_EMAIL
  value: ""
  description: User Email of GitHub acount to access GitHub repository.
- name: USER_NAME
  value: ""
  description: User name of GitHub account
- name: GIT_TOKEN
  value: ""
  description: GitHub token to access GitHub repository.
# parameters for the credentials used in the workflows with default values.
- name: LOCATION
  value: "eastus"
  description: Location of the resource group
# Optional parameters:
# if you want to use optional parameters, please uncomment the following lines
#- name: ELK_URI
#  value: ""
#  description: URI (hostname:port) for Elastic server, leave blank if you don't want to integrate ELK.
#- name: ELK_USER_NAME
#  value: ""
#  description: Account password for Elastic server, leave blank if you don't want to integrate ELK.
#- name: ELK_PSW
#  value: ""
#  description: Account password for Elastic server, leave blank if you don't want to integrate ELK.
