# This file contains the parameters for the credentials used in the workflows.
- name: ORC_SSOUSER
  value: ""
  description: "Oracle single sign-on userid."
- name: ORC_SSOPSW
  value: ""
  description: "Password for Oracle single sign-on userid."
- name: WDT_RUNTIMEPSW
  value: ""
  description: "Password for WebLogic Server and Runtime Deployment Tooling encryption."
- name: WLS_PSW
  value: ${WDT_RUNTIMEPSW}
  description: "Password for WebLogic Server and Runtime Deployment Tooling encryption."
# parameters for the credentials used in the workflows with default values.
- name: WLS_USERNAME
  value: "weblogic"
  description: "WebLogic Server user name."
- name: DB_PASSWORD
  value: "Secret123!"
  description: "Password for the database"
- name: LOCATION
  value: "eastus"
  description: "Location of the resource group"
